name: graph_nav_util unit tests

# Run on every push
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Make directory
        run: mkdir -p ~/spot_wrapper

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ~/spot_wrapper

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r ~/spot_wrapper/requirements.txt

      - name: Run tests
        run: python3 -m unittest discover ~/spot_wrapper/spot_wrapper/tests
